### ISSUE TITLE
make fixes based on code climate suggestions

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#71]
https://codeclimate.com/github/npm/marky-markdown/issues/categories/bugrisk

**Comment by zeke** [comment]
I'm not sure about [the suggestion](https://codeclimate.com/github/npm/marky-markdown/bin/marky-markdown.js) to use `throw` instead of `process.exit()`. Doing so will result in a bunch error output to the screen, when all we really want is usage:

```
❯ node bin/marky-markdown.js
/Users/z/zeke/marky-markdown/bin/marky-markdown.js:7
  throw new Error('Usage:\n\nmarky-markdown some.md > some.html')
  ^

Error: Usage:

marky-markdown some.md > some.html
  at Object.<anonymous> (/Users/z/zeke/marky-markdown/bin/marky-markdown.js:7:9)
  at Module._compile (module.js:398:26)
  at Object.Module._extensions..js (module.js:405:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:430:10)
  at startup (node.js:141:18)
  at node.js:980:3
```

https://twitter.com/zeke/status/684425698321158144

**Comment by ashleygwilliams** [comment]
closing. i don't think these checks are worthwhile.
